In [1]:
import numpy as np
A = np.array([[2, 9, 8, 0],
             [8, 7, 5, 6], 
             [3, 1, 0, 2], 
             [6, 5, 6, 8],
             [1, 0, 0, 4]])
A

array([[2, 9, 8, 0],
       [8, 7, 5, 6],
       [3, 1, 0, 2],
       [6, 5, 6, 8],
       [1, 0, 0, 4]])

In [2]:
A_tr = [list(i) for i in A]
A_tr = [list(i) for i in list(zip(*A_tr))]
A_tr = np.array(A_tr)
A_tr

array([[2, 8, 3, 6, 1],
       [9, 7, 1, 5, 0],
       [8, 5, 0, 6, 0],
       [0, 6, 2, 8, 4]])

In [3]:
# или в одну строку:
A_tr = np.array([list(i) for i in list(zip(*[list(i) for i in A]))])
A_tr

array([[2, 8, 3, 6, 1],
       [9, 7, 1, 5, 0],
       [8, 5, 0, 6, 0],
       [0, 6, 2, 8, 4]])

In [4]:
len(A)

5

In [5]:
# A_tr = [*A]
A_tr = np.array(list(zip(*[[*A][i] for i in range(len(A))])))
# A_tr = np.array(list(A_list))
A_tr
# A_tr = list(zip([*A][0], [*A][1], [*A][2], [*A][3], [*A][4]))
# A_tr = np.array(A_tr)
# A_tr

array([[2, 8, 3, 6, 1],
       [9, 7, 1, 5, 0],
       [8, 5, 0, 6, 0],
       [0, 6, 2, 8, 4]])

In [6]:
np.array_equal([[*A][i] for i in range(len(A))], [*A])

True

In [7]:
[*A]

[array([2, 9, 8, 0]),
 array([8, 7, 5, 6]),
 array([3, 1, 0, 2]),
 array([6, 5, 6, 8]),
 array([1, 0, 0, 4])]

In [8]:
A_tr = np.array([*zip(*A)])
A_tr

array([[2, 8, 3, 6, 1],
       [9, 7, 1, 5, 0],
       [8, 5, 0, 6, 0],
       [0, 6, 2, 8, 4]])

In [9]:
A_tr = np.array(list(zip(*A)))
A_tr

array([[2, 8, 3, 6, 1],
       [9, 7, 1, 5, 0],
       [8, 5, 0, 6, 0],
       [0, 6, 2, 8, 4]])

In [10]:
def transpose_list(list_of_lists):
    return [
        list(row)
        for row in zip(*list_of_lists)
    ]
transpose_list([list(i) for i in A])

[[2, 8, 3, 6, 1], [9, 7, 1, 5, 0], [8, 5, 0, 6, 0], [0, 6, 2, 8, 4]]